runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: pantai-kartini/index.html
  upload: pantai-kartini/index.html

- url: /(.*)
  static_files: pantai-kartini/\1
  upload: pantai-kartini/(.*)
